export const categories = [
  'Nəqliyyat',
  'Telefonlar',
  'Ev və bağ üçün',
  'Elektronika',
  'Daşınmaz əmlak',
  'Ehtiyat hissələri və aksesuarlar',
  'Xidmətlər və biznes',
  'Şəxsi əşyalar',
  'Məişət texnikası',
  'Uşaq aləmi',
  'Heyvanlar',
  'İş elanları',
  'Məktəblilər üçün',
  'Mağazalar',
  'Hobbi və asudə',
]
